[RF-669] Update to new Product Onboarding Process
RizeFinance/rize-sdks pull request #91
Opened 2021-07-19 19:50 UTC by ksalmon

## Ticket
https://gathering.atlassian.net/wiki/spaces/R3/pages/1778941972/Proposal+For+New+Onboarding+Flow+With+Multiple+Custodial+Accounts+Using+Products

Products: https://rize-developer-dev.netlify.app/#tag/Products
CustomerProducts: https://rize-developer-dev.netlify.app/#tag/Customer-Products

### New Steps!
**POST /customers with external_uid and email**

- Initializes an empty customer record

**GET /products**

- Returns the list of products available for your program and all requirments

- Not a required step if a client already knows their Product UID’s and requirements

**POST /compliance_workflows with customer_uid and compliance_plan_uid**

- Starts a compliance workflow process just like today

- Client continues acknowledging documents as necessary until complete

**PUT /customers/uid**

- Client independently updates all required PII for the Customer

**PUT /customers/uid/update_profile_responses**

- Client answers any required questions (if any) for the investor profile

**POST /customer_products with customer_uid and product_uid**

- This effectively becomes the new identity_verification endpoint

- This will verify that all Product requirements have been met

- For the FIRST product, this will automatically kick off the KYC process

- Upon KYC approval, all required custodial accounts will be created and the customer will be active
-
## Dependencies
- ...

## Changes
- ...

## Pre-Test Plan
- ...

## Test Plan
1. Pull down this branch.
2.

2021-07-21 14:43 UTC, RockinRonE requested changes
Some grammar updates.

Appreciate all the documentation!

2021-07-21 14:43 UTC, RockinRonE commented on README.md
> +The last step will trigger verification that all Product requirements have been met. After completion Rize will automatically kick off the KYC process if it the customers first product. Upon successf
Revised the paragraph, aka, I ran it through Grammarly:

The last step will trigger verification that all Product requirements have been met. After completion, Rize will automatically kick off the KYC process if it is the customer's first product. Upon successful creation, all required custodial accounts will be created, and the customer will be active. This is a billable event and is intentionally isolated for you to confirm that the Customer record is complete.

2021-07-21 14:43 UTC, RockinRonE commented on README.md
> +Each plan may come with questions that are required in order to complete the onboarding flow for the new customer. ([more info](docs.md#customer))
Each plan may come with questions that are required to complete the onboarding flow for the new customer.

2021-07-21 14:43 UTC, RockinRonE commented on README.md
> +Next we need to retrieve a list of products available for your program and all requirements for the new customer to complete.
Add a comma after Next

2021-07-21 14:43 UTC, RockinRonE commented on README.md
> +Create Customer is the first endpoint you will use to start the onboard flow.
Create Customer is the first endpoint to start the onboard flow. 

Active voice :)

2021-07-21 14:43 UTC, RockinRonE commented on README.md
> +Your first request to create empty customer with a external id and the users email and a customer object is returned with a uid.
I think this needs to be rewritten. Are you saying that the first request will return a customer object that contains an external id and the user's email? 

FYI: I noticed a pattern of forgetting to have "users" as "user's" when singular.

2021-07-21 14:43 UTC, RockinRonE commented on README.md
> +Creating a compliance workflow just requires the new customer UID and the compliance plan UID from the last two steps.
I would remove "just" as it's not necessary

2021-07-21 14:43 UTC, RockinRonE commented on README.md
>  Your request to the Compliance workflows endpoint initiates a Compliance Workflow for the
Sending a request to the Compliance workflow's endpoint initiates a Compliance Workflow for the onboarding customer. The Compliance Workflow contains disclosure and compliance documents that the Customer must acknowledge before opening a Custodial
Account.

2021-07-21 14:43 UTC, RockinRonE commented on README.md
>  statuses using the last names supplied with the Customer record. The statuses in the Rize
What is "undergo a statuses" ?

2021-07-21 14:43 UTC, RockinRonE commented on README.md
> +| Smith                                  | Manual Review                | The Custodian is unable to onboard the Customer through an automated process and additional information is required. |
Comma before "and"

2021-07-21 18:31 UTC, KramerJeff requested changes

2021-07-21 18:31 UTC, KramerJeff commented on README.md
> +| timeout     | The number of milliseconds before the each request times out | 80000     |
Should be: "The number of milliseconds before each request times out"

2021-07-21 18:31 UTC, KramerJeff commented on lib/core/customer-product.js
> +     * After completion Rize will automatically kick off the KYC process if it the customers first product.
After completion, Rize will automatically kick off the KYC process if it is the customer's first product.

2021-07-23 22:15 UTC, KramerJeff approved these changes

2021-07-23 22:15 UTC, KramerJeff commented
Grammar changes are all done, good work @ksalmon

2021-07-24 16:29 UTC, merged